import datetime as dt
import json


def generate_json_report(
    total_number_of_orders,
    total_revenue,
    top_5_products_by_revenue,
    top_5_customers_by_total_spend,
    revenue_by_category,
    file_name,
):
    timestamp = dt.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

    data = {
        "generated at": timestamp,
        "total number of order": total_number_of_orders,
        "total revenue": total_revenue,
        "top 5 products by revenue": top_5_products_by_revenue,
        "top 5 customers by total spend": top_5_customers_by_total_spend,
        "revenue by category": revenue_by_category,
    }
    try:
        with open(file_name, "w", encoding="utf-8") as file:
            json.dump(data, file, indent=4)
    except OSError as error:
        print(f"Could not create the report: {error}")


def initialize_markdown_report(
    total_number_of_orders,
    total_revenue,
    top_5_products_by_price,
    top_5_customers_by_total_spend,
    revenue_by_category,
    timestamp,
):
    report = f"""<h1 style="color: #274c77;text-align:center">Brightstone Logistics Report</h1>

**Generated:** {timestamp}

<h2 style="color: #6096ba;">Summary</h2>

- **Total orders:** {total_number_of_orders}
- **Total revenue:** €{total_revenue:,.2f}

<h2 style="color: #6096ba;">Top 5 Products by Price</h2>

"""

    for product in top_5_products_by_price:
        report += f"- **{product['product']}** : €{product['price']:,.2f}\n"

    report += "\n<h2 style='color: #6096ba;'>Top 5 Spending Customers</h2>\n\n"

    for customer, spending in top_5_customers_by_total_spend:
        report += f"- **{customer}** : €{spending:,.2f}\n"

    report += "\n<h2 style='color: #6096ba;'>Revenue by Category</h2>\n\n"

    for category, revenue in revenue_by_category:
        report += f"- **{category}** : €{revenue:,.2f}\n"

    report += (
        "\n\n## <h3 style='color: #6096ba;'>Notes </h3>\n"
        "- Report generated automatically from the provided order data.\n"
        "- Revenue is calculated as quantity × unit price.\n"
        "- Products are ranked by unit price.\n\n"
        "\n<hr>"
        "<p style='text-align: center; color: #777;'>"
        "Generated by: <strong>M.S.N</strong>"
        "</p>"
    )

    return report


def generate_markdown_report(
    total_number_of_orders,
    total_revenue,
    top_5_products_by_price,
    top_5_customers_by_total_spend,
    revenue_by_category,
    file_name,
):
    try:
        timestamp = dt.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

        report = initialize_markdown_report(
            total_number_of_orders,
            total_revenue,
            top_5_products_by_price,
            top_5_customers_by_total_spend,
            revenue_by_category,
            timestamp,
        )

        with open(file_name, "w", encoding="utf-8") as file:
            file.write(report)

    except OSError as error:
        print(f"Could not create the report: {error}")
